# Generated by Django 4.0.6 on 2022-07-26 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_alter_category_id_alter_comment_id_alter_genre_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='title',
            old_name='discription',
            new_name='description',
        ),
    ]
