# Generated by Django 2.2.16 on 2022-07-26 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_auto_20220726_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmationCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation_code', models.CharField(max_length=4, verbose_name='Confirmation code')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verify_code', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='VerifyCode',
        ),
        migrations.AddConstraint(
            model_name='confirmationcode',
            constraint=models.UniqueConstraint(fields=('username', 'confirmation_code'), name='unique_username_code'),
        ),
    ]
