# Generated by Django 2.2.16 on 2022-07-26 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0011_auto_20220726_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmationcode',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmation_code', to=settings.AUTH_USER_MODEL),
        ),
    ]
