# Generated by Django 2.2.16 on 2022-07-30 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0013_auto_20220730_0307'),
        ('reviews', '0014_auto_20220726_2253'),
    ]

    operations = [
    ]
