# Generated by Django 4.0.6 on 2022-07-30 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_rename_discription_title_description_and_more'),
        ('reviews', '0015_merge_20220730_2008'),
    ]

    operations = [
    ]
