# Generated by Django 2.2.16 on 2022-07-30 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0015_merge_20220730_2008'),
        ('reviews', '0008_rename_discription_title_description_and_more'),
    ]

    operations = [
    ]
