# Generated by Django 2.2.16 on 2022-07-31 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0017_auto_20220731_0303'),
        ('reviews', '0016_merge_20220730_2104'),
    ]

    operations = [
    ]
