# Generated by Django 2.2.19 on 2022-08-01 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0018_auto_20220801_1403'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-pk'], 'verbose_name_plural': 'Категории'},
        ),
    ]
