# Generated by Django 2.2.16 on 2022-08-01 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0018_merge_20220731_2105'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
