# Generated by Django 2.2.19 on 2022-08-02 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0023_auto_20220802_0034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-pub_date'], 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
    ]
