# Generated by Django 2.2.19 on 2022-08-02 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0024_auto_20220802_0037'),
        ('reviews', '0019_delete_user'),
    ]

    operations = [
    ]
